/*
node{
    stage("Build") {
            sh build.sh
    }
    stage("Test") {
            sh test.sh
    }
    stage("Deploy"){
            sh deploy.sh
    }
}
*/
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'sh runway/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh 'sh runway/test.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh 'sh runway/deploy.sh'
            }
        }
    }
}