/*
node{
    stage("Build") {
            sh build.sh
    }
    stage("Test") {
            sh test.sh
    }
    stage("Deploy"){
            sh deploy.sh
    }
}
*/
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh build.sh
            }
        }
        stage('Test') {
            steps {
                sh test.sh
            }
        }
        stage('Deploy') {
            steps {
                sh deploy.sh
            }
        }
    }
}